config:
  aws:region: us-east-1
  ceuplanner-infra:domainName: ceuplanner.com
  ceuplanner-infra:createHostedZone: "true"
  ceuplanner-infra:dbInstanceClass: db.t4g.micro
  ceuplanner-infra:dbAllocatedStorage: "20"
  ceuplanner-infra:apiImageTag: latest
  ceuplanner-infra:deployApiService: "false"
  ceuplanner-infra:dbName: ceuplanner
  ceuplanner-infra:dbUsername: ceu_admin
encryptionsalt: v1:k/5nnmj/FQk=:v1:Pa+hYK7yEMpbDW3T:rZ7E3ECXRV4buRKFt5ZCqNMsU7PKlQ==
